import { Video } from "./api";

const DEMO_VIDEO_URL = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4";

const creators = [
  { id: "creator1", name: "FixItPro" },
  { id: "creator2", name: "HomeHelper" },
  { id: "creator3", name: "DIYMaster" },
  { id: "creator4", name: "CleanQueen" },
  { id: "creator5", name: "TechTips" },
  { id: "creator6", name: "AutoFixer" },
  { id: "creator7", name: "KitchenWiz" },
  { id: "creator8", name: "PlumbPro" },
  { id: "creator9", name: "SparkSafe" },
  { id: "creator10", name: "QuickFixer" },
];

const getCreator = (index: number) => creators[index % creators.length];
const getDate = (daysAgo: number) => new Date(Date.now() - daysAgo * 86400000).toISOString();
const randomLikes = () => Math.floor(Math.random() * 900) + 100;
const randomDuration = () => Math.floor(Math.random() * 35) + 25;

export const sampleVideos: Video[] = [
  // KITCHEN (12 videos)
  {
    id: "k1",
    title: "Fix a Dripping Kitchen Faucet",
    description: "Stop that annoying drip in under a minute with this quick fix.",
    category: "kitchen",
    tags: ["faucet", "drip", "kitchen", "water", "quick fix"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 45,
    likesCount: 892,
    commentsEnabled: true,
    authorId: "creator1",
    authorName: "FixItPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(1),
  },
  {
    id: "k2",
    title: "Sharpen Kitchen Knives Like a Pro",
    description: "Keep your knives razor sharp with proper sharpening technique.",
    category: "kitchen",
    tags: ["knife", "sharpen", "kitchen", "tools", "cooking"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 52,
    likesCount: 756,
    commentsEnabled: true,
    authorId: "creator7",
    authorName: "KitchenWiz",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(2),
  },
  {
    id: "k3",
    title: "Unclog a Kitchen Sink Naturally",
    description: "Use baking soda and vinegar to clear your kitchen drain.",
    category: "kitchen",
    tags: ["sink", "clog", "natural", "drain", "kitchen"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 48,
    likesCount: 645,
    commentsEnabled: true,
    authorId: "creator1",
    authorName: "FixItPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(3),
  },
  {
    id: "k4",
    title: "Fix a Loose Cabinet Handle",
    description: "Tighten or replace cabinet handles in seconds.",
    category: "kitchen",
    tags: ["cabinet", "handle", "kitchen", "furniture", "quick fix"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 32,
    likesCount: 423,
    commentsEnabled: true,
    authorId: "creator2",
    authorName: "HomeHelper",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(5),
  },
  {
    id: "k5",
    title: "Clean Oven Without Harsh Chemicals",
    description: "Natural cleaning method for a sparkling oven.",
    category: "kitchen",
    tags: ["oven", "clean", "natural", "kitchen", "baking soda"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 55,
    likesCount: 567,
    commentsEnabled: true,
    authorId: "creator4",
    authorName: "CleanQueen",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(7),
  },
  {
    id: "k6",
    title: "Fix a Garbage Disposal Jam",
    description: "Safely unjam your garbage disposal in 30 seconds.",
    category: "kitchen",
    tags: ["disposal", "jam", "kitchen", "plumbing", "fix"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 35,
    likesCount: 734,
    commentsEnabled: true,
    authorId: "creator8",
    authorName: "PlumbPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(9),
  },
  {
    id: "k7",
    title: "Replace Refrigerator Water Filter",
    description: "Step-by-step guide to changing your fridge water filter.",
    category: "kitchen",
    tags: ["refrigerator", "filter", "water", "maintenance", "kitchen"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 42,
    likesCount: 389,
    commentsEnabled: true,
    authorId: "creator2",
    authorName: "HomeHelper",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(11),
  },
  {
    id: "k8",
    title: "Fix a Microwave That Won't Heat",
    description: "Common fix for microwaves that spin but don't heat food.",
    category: "kitchen",
    tags: ["microwave", "repair", "kitchen", "appliance", "heat"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 58,
    likesCount: 623,
    commentsEnabled: true,
    authorId: "creator5",
    authorName: "TechTips",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(13),
  },
  {
    id: "k9",
    title: "Organize Under-Sink Cabinet",
    description: "Maximize storage space under your kitchen sink.",
    category: "kitchen",
    tags: ["organize", "cabinet", "storage", "kitchen", "space"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 47,
    likesCount: 445,
    commentsEnabled: true,
    authorId: "creator4",
    authorName: "CleanQueen",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(15),
  },
  {
    id: "k10",
    title: "Fix a Dishwasher Not Draining",
    description: "Troubleshoot and fix common dishwasher drainage issues.",
    category: "kitchen",
    tags: ["dishwasher", "drain", "repair", "kitchen", "appliance"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 54,
    likesCount: 678,
    commentsEnabled: true,
    authorId: "creator1",
    authorName: "FixItPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(17),
  },

  // BATHROOM (10 videos)
  {
    id: "b1",
    title: "Fix a Running Toilet",
    description: "Stop water waste with this quick toilet flapper fix.",
    category: "bathroom",
    tags: ["toilet", "running", "water", "bathroom", "fix"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 48,
    likesCount: 945,
    commentsEnabled: true,
    authorId: "creator8",
    authorName: "PlumbPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(2),
  },
  {
    id: "b2",
    title: "Unclog a Bathroom Drain",
    description: "Clear hair and soap buildup from your bathroom drain.",
    category: "bathroom",
    tags: ["drain", "clog", "hair", "bathroom", "sink"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 42,
    likesCount: 823,
    commentsEnabled: true,
    authorId: "creator1",
    authorName: "FixItPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(4),
  },
  {
    id: "b3",
    title: "Replace a Showerhead",
    description: "Upgrade your showerhead in under 2 minutes.",
    category: "bathroom",
    tags: ["shower", "showerhead", "replace", "bathroom", "water"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 38,
    likesCount: 567,
    commentsEnabled: true,
    authorId: "creator8",
    authorName: "PlumbPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(6),
  },
  {
    id: "b4",
    title: "Fix a Loose Toilet Seat",
    description: "Tighten a wobbly toilet seat with basic tools.",
    category: "bathroom",
    tags: ["toilet", "seat", "loose", "tighten", "bathroom"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 28,
    likesCount: 456,
    commentsEnabled: true,
    authorId: "creator2",
    authorName: "HomeHelper",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(8),
  },
  {
    id: "b5",
    title: "Remove Bathroom Mold Safely",
    description: "Eliminate mold from bathroom tiles and grout.",
    category: "bathroom",
    tags: ["mold", "clean", "grout", "bathroom", "tiles"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 52,
    likesCount: 734,
    commentsEnabled: true,
    authorId: "creator4",
    authorName: "CleanQueen",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(10),
  },
  {
    id: "b6",
    title: "Fix a Leaky Bathroom Faucet",
    description: "Stop that annoying bathroom faucet drip.",
    category: "bathroom",
    tags: ["faucet", "leak", "drip", "bathroom", "water"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 45,
    likesCount: 612,
    commentsEnabled: true,
    authorId: "creator1",
    authorName: "FixItPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(12),
  },
  {
    id: "b7",
    title: "Install a Towel Bar",
    description: "Mount a towel bar securely in any bathroom.",
    category: "bathroom",
    tags: ["towel", "bar", "install", "bathroom", "mount"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 55,
    likesCount: 389,
    commentsEnabled: true,
    authorId: "creator3",
    authorName: "DIYMaster",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(14),
  },
  {
    id: "b8",
    title: "Fix Bathroom Exhaust Fan",
    description: "Quiet a noisy bathroom fan or replace it entirely.",
    category: "bathroom",
    tags: ["fan", "exhaust", "noise", "bathroom", "ventilation"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 58,
    likesCount: 478,
    commentsEnabled: true,
    authorId: "creator9",
    authorName: "SparkSafe",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(16),
  },
  {
    id: "b9",
    title: "Re-caulk Bathtub Edges",
    description: "Remove old caulk and apply fresh seal around your tub.",
    category: "bathroom",
    tags: ["caulk", "bathtub", "seal", "bathroom", "waterproof"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 60,
    likesCount: 534,
    commentsEnabled: true,
    authorId: "creator8",
    authorName: "PlumbPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(18),
  },
  {
    id: "b10",
    title: "Adjust Toilet Float Valve",
    description: "Fix water level issues by adjusting the float valve.",
    category: "bathroom",
    tags: ["toilet", "float", "valve", "water level", "bathroom"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 35,
    likesCount: 423,
    commentsEnabled: true,
    authorId: "creator8",
    authorName: "PlumbPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(20),
  },

  // CLEANING (10 videos)
  {
    id: "c1",
    title: "Remove Carpet Stains Instantly",
    description: "Get rid of stubborn carpet stains with household items.",
    category: "cleaning",
    tags: ["carpet", "stain", "clean", "remove", "home"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 42,
    likesCount: 867,
    commentsEnabled: true,
    authorId: "creator4",
    authorName: "CleanQueen",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(1),
  },
  {
    id: "c2",
    title: "Clean Windows Streak-Free",
    description: "Professional window cleaning technique for crystal clear glass.",
    category: "cleaning",
    tags: ["windows", "glass", "streak-free", "clean", "shine"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 38,
    likesCount: 654,
    commentsEnabled: true,
    authorId: "creator4",
    authorName: "CleanQueen",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(3),
  },
  {
    id: "c3",
    title: "Deep Clean Your Mattress",
    description: "Remove dust mites and freshen your mattress naturally.",
    category: "cleaning",
    tags: ["mattress", "deep clean", "dust mites", "bedroom", "fresh"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 55,
    likesCount: 723,
    commentsEnabled: true,
    authorId: "creator4",
    authorName: "CleanQueen",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(5),
  },
  {
    id: "c4",
    title: "Remove Grease from Stovetop",
    description: "Cut through baked-on grease with this simple method.",
    category: "cleaning",
    tags: ["grease", "stovetop", "kitchen", "clean", "degrease"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 45,
    likesCount: 589,
    commentsEnabled: true,
    authorId: "creator7",
    authorName: "KitchenWiz",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(7),
  },
  {
    id: "c5",
    title: "Clean Hardwood Floors Safely",
    description: "Best practices for cleaning hardwood without damage.",
    category: "cleaning",
    tags: ["hardwood", "floor", "clean", "wood", "safe"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 48,
    likesCount: 512,
    commentsEnabled: true,
    authorId: "creator4",
    authorName: "CleanQueen",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(9),
  },
  {
    id: "c6",
    title: "Remove Pet Hair from Furniture",
    description: "Quick tricks to remove pet hair from sofas and chairs.",
    category: "cleaning",
    tags: ["pet hair", "furniture", "sofa", "clean", "remove"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 35,
    likesCount: 678,
    commentsEnabled: true,
    authorId: "creator4",
    authorName: "CleanQueen",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(11),
  },
  {
    id: "c7",
    title: "Clean Blinds Without Removing",
    description: "Easy way to dust and clean window blinds in place.",
    category: "cleaning",
    tags: ["blinds", "dust", "windows", "clean", "quick"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 32,
    likesCount: 445,
    commentsEnabled: true,
    authorId: "creator2",
    authorName: "HomeHelper",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(13),
  },
  {
    id: "c8",
    title: "Descale Coffee Maker",
    description: "Remove mineral buildup from your coffee machine.",
    category: "cleaning",
    tags: ["coffee maker", "descale", "clean", "appliance", "vinegar"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 40,
    likesCount: 534,
    commentsEnabled: true,
    authorId: "creator7",
    authorName: "KitchenWiz",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(15),
  },
  {
    id: "c9",
    title: "Clean Ceiling Fan Blades",
    description: "Dust ceiling fan blades without making a mess.",
    category: "cleaning",
    tags: ["ceiling fan", "dust", "blades", "clean", "home"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 28,
    likesCount: 389,
    commentsEnabled: true,
    authorId: "creator2",
    authorName: "HomeHelper",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(17),
  },
  {
    id: "c10",
    title: "Remove Water Stains from Wood",
    description: "Fix white water rings on wooden furniture.",
    category: "cleaning",
    tags: ["water stain", "wood", "furniture", "remove", "fix"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 38,
    likesCount: 467,
    commentsEnabled: true,
    authorId: "creator3",
    authorName: "DIYMaster",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(19),
  },

  // LAUNDRY (8 videos)
  {
    id: "l1",
    title: "Clean Your Washing Machine",
    description: "Remove odors and buildup from your washer naturally.",
    category: "laundry",
    tags: ["washing machine", "clean", "odor", "maintenance", "laundry"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 48,
    likesCount: 789,
    commentsEnabled: true,
    authorId: "creator4",
    authorName: "CleanQueen",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(2),
  },
  {
    id: "l2",
    title: "Remove Grass Stains",
    description: "Get rid of stubborn grass stains from clothes.",
    category: "laundry",
    tags: ["grass", "stain", "clothes", "remove", "laundry"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 35,
    likesCount: 567,
    commentsEnabled: true,
    authorId: "creator4",
    authorName: "CleanQueen",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(4),
  },
  {
    id: "l3",
    title: "Fix a Dryer That Won't Heat",
    description: "Troubleshoot common dryer heating problems.",
    category: "laundry",
    tags: ["dryer", "heat", "repair", "appliance", "laundry"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 55,
    likesCount: 678,
    commentsEnabled: true,
    authorId: "creator5",
    authorName: "TechTips",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(6),
  },
  {
    id: "l4",
    title: "Remove Oil Stains from Clothes",
    description: "Pre-treat and remove cooking oil stains effectively.",
    category: "laundry",
    tags: ["oil", "stain", "clothes", "pre-treat", "laundry"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 42,
    likesCount: 534,
    commentsEnabled: true,
    authorId: "creator4",
    authorName: "CleanQueen",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(8),
  },
  {
    id: "l5",
    title: "Clean Dryer Lint Trap Deep",
    description: "Prevent fires by deep cleaning your lint trap area.",
    category: "laundry",
    tags: ["dryer", "lint", "fire safety", "clean", "maintenance"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 38,
    likesCount: 823,
    commentsEnabled: true,
    authorId: "creator10",
    authorName: "QuickFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(10),
  },
  {
    id: "l6",
    title: "Remove Red Wine Stains",
    description: "Emergency treatment for red wine spills on fabric.",
    category: "laundry",
    tags: ["wine", "stain", "fabric", "emergency", "remove"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 32,
    likesCount: 645,
    commentsEnabled: true,
    authorId: "creator4",
    authorName: "CleanQueen",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(12),
  },
  {
    id: "l7",
    title: "Fix Washer That Won't Drain",
    description: "Clear blockages and fix drainage issues.",
    category: "laundry",
    tags: ["washer", "drain", "clog", "repair", "laundry"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 52,
    likesCount: 567,
    commentsEnabled: true,
    authorId: "creator1",
    authorName: "FixItPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(14),
  },
  {
    id: "l8",
    title: "Whiten Yellowed Clothes",
    description: "Restore white clothes without harsh bleach.",
    category: "laundry",
    tags: ["white", "yellow", "clothes", "brighten", "natural"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 45,
    likesCount: 489,
    commentsEnabled: true,
    authorId: "creator4",
    authorName: "CleanQueen",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(16),
  },

  // ELECTRONICS (10 videos)
  {
    id: "e1",
    title: "Reset Your Phone Battery",
    description: "Calibrate your phone battery for better performance.",
    category: "electronics",
    tags: ["phone", "battery", "calibrate", "mobile", "performance"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 38,
    likesCount: 912,
    commentsEnabled: true,
    authorId: "creator5",
    authorName: "TechTips",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(1),
  },
  {
    id: "e2",
    title: "Fix Slow WiFi Connection",
    description: "Optimize your router placement and settings.",
    category: "electronics",
    tags: ["wifi", "router", "internet", "speed", "network"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 52,
    likesCount: 845,
    commentsEnabled: true,
    authorId: "creator5",
    authorName: "TechTips",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(3),
  },
  {
    id: "e3",
    title: "Clean Phone Charging Port",
    description: "Safely clean debris from your phone's charging port.",
    category: "electronics",
    tags: ["phone", "charging", "port", "clean", "fix"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 28,
    likesCount: 723,
    commentsEnabled: true,
    authorId: "creator5",
    authorName: "TechTips",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(5),
  },
  {
    id: "e4",
    title: "Fix TV Remote Not Working",
    description: "Troubleshoot common TV remote issues.",
    category: "electronics",
    tags: ["tv", "remote", "fix", "batteries", "infrared"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 35,
    likesCount: 534,
    commentsEnabled: true,
    authorId: "creator5",
    authorName: "TechTips",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(7),
  },
  {
    id: "e5",
    title: "Extend Laptop Battery Life",
    description: "Settings and habits for longer laptop battery.",
    category: "electronics",
    tags: ["laptop", "battery", "extend", "power", "settings"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 48,
    likesCount: 678,
    commentsEnabled: true,
    authorId: "creator5",
    authorName: "TechTips",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(9),
  },
  {
    id: "e6",
    title: "Fix Bluetooth Connection Issues",
    description: "Resolve common Bluetooth pairing problems.",
    category: "electronics",
    tags: ["bluetooth", "pairing", "connection", "fix", "wireless"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 42,
    likesCount: 589,
    commentsEnabled: true,
    authorId: "creator5",
    authorName: "TechTips",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(11),
  },
  {
    id: "e7",
    title: "Clean Your Keyboard Properly",
    description: "Deep clean a keyboard without damaging it.",
    category: "electronics",
    tags: ["keyboard", "clean", "computer", "dust", "maintenance"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 45,
    likesCount: 456,
    commentsEnabled: true,
    authorId: "creator5",
    authorName: "TechTips",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(13),
  },
  {
    id: "e8",
    title: "Fix Frozen Computer Screen",
    description: "What to do when your computer freezes up.",
    category: "electronics",
    tags: ["computer", "frozen", "restart", "troubleshoot", "fix"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 32,
    likesCount: 612,
    commentsEnabled: true,
    authorId: "creator5",
    authorName: "TechTips",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(15),
  },
  {
    id: "e9",
    title: "Set Up Smart Home Device",
    description: "Quick guide to connecting smart home devices.",
    category: "electronics",
    tags: ["smart home", "wifi", "setup", "alexa", "google"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 55,
    likesCount: 534,
    commentsEnabled: true,
    authorId: "creator5",
    authorName: "TechTips",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(17),
  },
  {
    id: "e10",
    title: "Fix Headphone Jack Issues",
    description: "Troubleshoot audio problems with headphone jacks.",
    category: "electronics",
    tags: ["headphone", "jack", "audio", "fix", "sound"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 38,
    likesCount: 423,
    commentsEnabled: true,
    authorId: "creator5",
    authorName: "TechTips",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(19),
  },

  // CAR & MOTOR (10 videos)
  {
    id: "car1",
    title: "Fix a Flat Tire in 5 Minutes",
    description: "Emergency roadside tire change when you're stranded.",
    category: "car",
    tags: ["tire", "flat", "emergency", "roadside", "change"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 58,
    likesCount: 1245,
    commentsEnabled: true,
    authorId: "creator6",
    authorName: "AutoFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(1),
  },
  {
    id: "car2",
    title: "Change Your Car Oil",
    description: "DIY oil change to save money on maintenance.",
    category: "car",
    tags: ["oil", "change", "maintenance", "car", "DIY"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 60,
    likesCount: 967,
    commentsEnabled: true,
    authorId: "creator6",
    authorName: "AutoFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(3),
  },
  {
    id: "car3",
    title: "Replace Windshield Wipers",
    description: "Quick wiper blade replacement for clear visibility.",
    category: "car",
    tags: ["wipers", "windshield", "replace", "visibility", "rain"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 32,
    likesCount: 678,
    commentsEnabled: true,
    authorId: "creator6",
    authorName: "AutoFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(5),
  },
  {
    id: "car4",
    title: "Jump Start a Dead Battery",
    description: "Safely jump start your car with jumper cables.",
    category: "car",
    tags: ["battery", "jump start", "dead", "cables", "emergency"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 45,
    likesCount: 1123,
    commentsEnabled: true,
    authorId: "creator6",
    authorName: "AutoFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(7),
  },
  {
    id: "car5",
    title: "Check and Add Coolant",
    description: "Prevent overheating by maintaining coolant levels.",
    category: "car",
    tags: ["coolant", "overheating", "radiator", "maintenance", "car"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 38,
    likesCount: 534,
    commentsEnabled: true,
    authorId: "creator6",
    authorName: "AutoFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(9),
  },
  {
    id: "car6",
    title: "Replace Air Filter",
    description: "Improve engine performance with a new air filter.",
    category: "car",
    tags: ["air filter", "engine", "replace", "performance", "maintenance"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 35,
    likesCount: 456,
    commentsEnabled: true,
    authorId: "creator6",
    authorName: "AutoFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(11),
  },
  {
    id: "car7",
    title: "Fix Minor Car Scratches",
    description: "Remove light scratches with household items.",
    category: "car",
    tags: ["scratch", "paint", "fix", "bodywork", "polish"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 48,
    likesCount: 789,
    commentsEnabled: true,
    authorId: "creator6",
    authorName: "AutoFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(13),
  },
  {
    id: "car8",
    title: "Check Tire Pressure",
    description: "Proper tire inflation for safety and fuel economy.",
    category: "car",
    tags: ["tire", "pressure", "safety", "fuel", "maintenance"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 28,
    likesCount: 567,
    commentsEnabled: true,
    authorId: "creator6",
    authorName: "AutoFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(15),
  },
  {
    id: "car9",
    title: "Replace Headlight Bulb",
    description: "Change a burnt out headlight bulb yourself.",
    category: "car",
    tags: ["headlight", "bulb", "replace", "lights", "night"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 42,
    likesCount: 623,
    commentsEnabled: true,
    authorId: "creator6",
    authorName: "AutoFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(17),
  },
  {
    id: "car10",
    title: "Clean Foggy Headlights",
    description: "Restore cloudy headlights to like-new condition.",
    category: "car",
    tags: ["headlight", "foggy", "clean", "restore", "visibility"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 52,
    likesCount: 734,
    commentsEnabled: true,
    authorId: "creator6",
    authorName: "AutoFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(19),
  },

  // TOOLS & DIY (10 videos)
  {
    id: "t1",
    title: "Fix a Squeaky Door Hinge",
    description: "Stop that annoying squeak in seconds.",
    category: "tools",
    tags: ["door", "hinge", "squeak", "oil", "quick fix"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 28,
    likesCount: 823,
    commentsEnabled: true,
    authorId: "creator3",
    authorName: "DIYMaster",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(1),
  },
  {
    id: "t2",
    title: "Replace a Light Switch",
    description: "Safely replace a broken light switch.",
    category: "tools",
    tags: ["light", "switch", "electrical", "replace", "safety"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 58,
    likesCount: 734,
    commentsEnabled: true,
    authorId: "creator9",
    authorName: "SparkSafe",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(3),
  },
  {
    id: "t3",
    title: "Hang a Picture Frame Level",
    description: "Get picture frames perfectly straight every time.",
    category: "tools",
    tags: ["picture", "frame", "hang", "level", "wall"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 35,
    likesCount: 567,
    commentsEnabled: true,
    authorId: "creator3",
    authorName: "DIYMaster",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(5),
  },
  {
    id: "t4",
    title: "Patch a Hole in Drywall",
    description: "Repair small to medium holes in your walls.",
    category: "tools",
    tags: ["drywall", "patch", "hole", "wall", "repair"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 55,
    likesCount: 678,
    commentsEnabled: true,
    authorId: "creator3",
    authorName: "DIYMaster",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(7),
  },
  {
    id: "t5",
    title: "Install a Smoke Detector",
    description: "Properly mount and test a smoke detector.",
    category: "tools",
    tags: ["smoke detector", "safety", "install", "fire", "home"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 42,
    likesCount: 534,
    commentsEnabled: true,
    authorId: "creator9",
    authorName: "SparkSafe",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(9),
  },
  {
    id: "t6",
    title: "Fix a Stuck Window",
    description: "Free a window that won't open or close properly.",
    category: "tools",
    tags: ["window", "stuck", "fix", "slide", "lubricate"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 38,
    likesCount: 456,
    commentsEnabled: true,
    authorId: "creator2",
    authorName: "HomeHelper",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(11),
  },
  {
    id: "t7",
    title: "Replace Outlet Cover",
    description: "Update old outlet covers for a fresh look.",
    category: "tools",
    tags: ["outlet", "cover", "replace", "electrical", "decor"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 25,
    likesCount: 389,
    commentsEnabled: true,
    authorId: "creator9",
    authorName: "SparkSafe",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(13),
  },
  {
    id: "t8",
    title: "Tighten Loose Door Knob",
    description: "Fix a wobbly door handle in minutes.",
    category: "tools",
    tags: ["door", "knob", "loose", "tighten", "fix"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 32,
    likesCount: 467,
    commentsEnabled: true,
    authorId: "creator2",
    authorName: "HomeHelper",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(15),
  },
  {
    id: "t9",
    title: "Fix Stripped Screw Hole",
    description: "Repair a stripped screw hole in wood or drywall.",
    category: "tools",
    tags: ["screw", "stripped", "hole", "repair", "wood"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 35,
    likesCount: 534,
    commentsEnabled: true,
    authorId: "creator3",
    authorName: "DIYMaster",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(17),
  },
  {
    id: "t10",
    title: "Install a Deadbolt Lock",
    description: "Add security with a new deadbolt lock.",
    category: "tools",
    tags: ["deadbolt", "lock", "security", "door", "install"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 60,
    likesCount: 678,
    commentsEnabled: true,
    authorId: "creator3",
    authorName: "DIYMaster",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(19),
  },

  // PLUMBING (8 videos)
  {
    id: "p1",
    title: "Fix a Leaking Pipe Joint",
    description: "Stop pipe leaks with plumber's tape and compound.",
    category: "plumbing",
    tags: ["pipe", "leak", "joint", "tape", "fix"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 45,
    likesCount: 867,
    commentsEnabled: true,
    authorId: "creator8",
    authorName: "PlumbPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(2),
  },
  {
    id: "p2",
    title: "Clear a Clogged P-Trap",
    description: "Remove and clean the P-trap under your sink.",
    category: "plumbing",
    tags: ["p-trap", "clog", "sink", "drain", "clean"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 48,
    likesCount: 723,
    commentsEnabled: true,
    authorId: "creator8",
    authorName: "PlumbPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(4),
  },
  {
    id: "p3",
    title: "Replace Toilet Fill Valve",
    description: "Fix a toilet that won't stop running.",
    category: "plumbing",
    tags: ["toilet", "fill valve", "replace", "running", "repair"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 55,
    likesCount: 645,
    commentsEnabled: true,
    authorId: "creator8",
    authorName: "PlumbPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(6),
  },
  {
    id: "p4",
    title: "Stop a Dripping Faucet",
    description: "Replace faucet washers to stop the drip.",
    category: "plumbing",
    tags: ["faucet", "drip", "washer", "replace", "fix"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 42,
    likesCount: 589,
    commentsEnabled: true,
    authorId: "creator1",
    authorName: "FixItPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(8),
  },
  {
    id: "p5",
    title: "Install Water Shut-Off Valve",
    description: "Add an emergency shut-off valve to any fixture.",
    category: "plumbing",
    tags: ["shut-off", "valve", "water", "install", "emergency"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 58,
    likesCount: 534,
    commentsEnabled: true,
    authorId: "creator8",
    authorName: "PlumbPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(10),
  },
  {
    id: "p6",
    title: "Fix Low Water Pressure",
    description: "Diagnose and fix common low pressure issues.",
    category: "plumbing",
    tags: ["water pressure", "low", "fix", "aerator", "pipes"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 52,
    likesCount: 678,
    commentsEnabled: true,
    authorId: "creator8",
    authorName: "PlumbPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(12),
  },
  {
    id: "p7",
    title: "Replace Sink Faucet",
    description: "Install a new kitchen or bathroom faucet.",
    category: "plumbing",
    tags: ["faucet", "replace", "sink", "install", "upgrade"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 60,
    likesCount: 567,
    commentsEnabled: true,
    authorId: "creator8",
    authorName: "PlumbPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(14),
  },
  {
    id: "p8",
    title: "Thaw Frozen Pipes Safely",
    description: "Safely thaw frozen pipes without bursting them.",
    category: "plumbing",
    tags: ["frozen", "pipes", "thaw", "winter", "emergency"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 48,
    likesCount: 823,
    commentsEnabled: true,
    authorId: "creator8",
    authorName: "PlumbPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(16),
  },

  // EMERGENCY (10 videos)
  {
    id: "em1",
    title: "Stop Bleeding Quickly",
    description: "First aid for cuts and minor wounds.",
    category: "emergency",
    tags: ["bleeding", "first aid", "wound", "cut", "emergency"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 35,
    likesCount: 1456,
    commentsEnabled: true,
    authorId: "creator10",
    authorName: "QuickFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(1),
  },
  {
    id: "em2",
    title: "Stop Water Leak Emergency",
    description: "Quick fix to stop water damage before the plumber arrives.",
    category: "emergency",
    tags: ["water", "leak", "emergency", "damage", "quick fix"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 32,
    likesCount: 1234,
    commentsEnabled: true,
    authorId: "creator1",
    authorName: "FixItPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(2),
  },
  {
    id: "em3",
    title: "Put Out Kitchen Fire",
    description: "How to safely extinguish common kitchen fires.",
    category: "emergency",
    tags: ["fire", "kitchen", "safety", "extinguish", "emergency"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 28,
    likesCount: 1567,
    commentsEnabled: true,
    authorId: "creator10",
    authorName: "QuickFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(3),
  },
  {
    id: "em4",
    title: "Turn Off Main Water Valve",
    description: "Locate and shut off your home's main water supply.",
    category: "emergency",
    tags: ["water", "valve", "shut off", "main", "emergency"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 25,
    likesCount: 934,
    commentsEnabled: true,
    authorId: "creator8",
    authorName: "PlumbPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(4),
  },
  {
    id: "em5",
    title: "Unlock a Door Without Key",
    description: "Emergency entry techniques when locked out.",
    category: "emergency",
    tags: ["door", "lock", "unlock", "locked out", "emergency"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 45,
    likesCount: 1089,
    commentsEnabled: true,
    authorId: "creator10",
    authorName: "QuickFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(5),
  },
  {
    id: "em6",
    title: "Fix Broken Window Temporarily",
    description: "Secure a broken window until replacement.",
    category: "emergency",
    tags: ["window", "broken", "temporary", "secure", "emergency"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 38,
    likesCount: 678,
    commentsEnabled: true,
    authorId: "creator2",
    authorName: "HomeHelper",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(6),
  },
  {
    id: "em7",
    title: "Reset Tripped Circuit Breaker",
    description: "Safely reset a tripped breaker and restore power.",
    category: "emergency",
    tags: ["breaker", "circuit", "power", "electrical", "reset"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 32,
    likesCount: 856,
    commentsEnabled: true,
    authorId: "creator9",
    authorName: "SparkSafe",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(7),
  },
  {
    id: "em8",
    title: "Stop Gas Leak Emergency",
    description: "What to do if you smell gas in your home.",
    category: "emergency",
    tags: ["gas", "leak", "safety", "emergency", "evacuate"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 28,
    likesCount: 1345,
    commentsEnabled: true,
    authorId: "creator10",
    authorName: "QuickFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(8),
  },
  {
    id: "em9",
    title: "Unclog Toilet Without Plunger",
    description: "Emergency toilet fix with household items.",
    category: "emergency",
    tags: ["toilet", "clog", "plunger", "emergency", "bathroom"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 35,
    likesCount: 978,
    commentsEnabled: true,
    authorId: "creator1",
    authorName: "FixItPro",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(9),
  },
  {
    id: "em10",
    title: "Emergency Phone Charger Hack",
    description: "Charge your phone with minimal equipment.",
    category: "emergency",
    tags: ["phone", "charger", "battery", "power", "emergency"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 42,
    likesCount: 756,
    commentsEnabled: true,
    authorId: "creator5",
    authorName: "TechTips",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(10),
  },

  // OTHER (4 videos)
  {
    id: "o1",
    title: "Remove Stuck Ring from Finger",
    description: "Safe techniques to remove a tight ring.",
    category: "other",
    tags: ["ring", "stuck", "remove", "finger", "tip"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 32,
    likesCount: 567,
    commentsEnabled: true,
    authorId: "creator10",
    authorName: "QuickFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(3),
  },
  {
    id: "o2",
    title: "Remove Stripped Screw",
    description: "Extract a screw with a stripped head.",
    category: "other",
    tags: ["screw", "stripped", "remove", "extract", "tools"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 38,
    likesCount: 645,
    commentsEnabled: true,
    authorId: "creator3",
    authorName: "DIYMaster",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(6),
  },
  {
    id: "o3",
    title: "Fix a Zipper That Won't Close",
    description: "Repair a broken zipper on clothes or bags.",
    category: "other",
    tags: ["zipper", "fix", "clothes", "repair", "sewing"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 35,
    likesCount: 489,
    commentsEnabled: true,
    authorId: "creator4",
    authorName: "CleanQueen",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(9),
  },
  {
    id: "o4",
    title: "Remove Super Glue from Skin",
    description: "Safely remove super glue without damage.",
    category: "other",
    tags: ["super glue", "skin", "remove", "safety", "adhesive"],
    videoUrl: DEMO_VIDEO_URL,
    thumbnailUrl: undefined,
    duration: 28,
    likesCount: 534,
    commentsEnabled: true,
    authorId: "creator10",
    authorName: "QuickFixer",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(12),
  },

  // REAL YOUTUBE TUTORIALS (5 videos) - no videoUrl, use Linking to open YouTube
  {
    id: "yt1",
    title: "How to Fix a Leaky Faucet",
    description: "Learn how to fix a dripping faucet in your bathroom or kitchen. This step-by-step guide shows you how to replace washers and O-rings to stop that annoying drip.",
    category: "plumbing",
    tags: ["faucet", "leak", "plumbing", "diy", "repair", "water"],
    thumbnailUrl: "https://img.youtube.com/vi/NZdMRYGSN4c/maxresdefault.jpg",
    duration: 480,
    likesCount: 15234,
    commentsEnabled: true,
    authorId: "youtube_creator",
    authorName: "Home Repair Tutor",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(0),
    isYouTube: true,
    youtubeId: "NZdMRYGSN4c",
  },
  {
    id: "yt2",
    title: "How to Unclog a Drain Without Chemicals",
    description: "Safely unclog your sink or bathtub drain using simple household tools. No harsh chemicals needed! Works for kitchen and bathroom drains.",
    category: "plumbing",
    tags: ["drain", "clog", "plumbing", "natural", "unclog", "sink"],
    thumbnailUrl: "https://img.youtube.com/vi/Lmb5D2zF5Lc/maxresdefault.jpg",
    duration: 390,
    likesCount: 28456,
    commentsEnabled: true,
    authorId: "youtube_creator2",
    authorName: "See Jane Drill",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(1),
    isYouTube: true,
    youtubeId: "Lmb5D2zF5Lc",
  },
  {
    id: "yt3",
    title: "How to Reset a Tripped Circuit Breaker",
    description: "Learn how to safely reset a tripped circuit breaker in your home. Understand what causes breakers to trip and when to call an electrician.",
    category: "electronics",
    tags: ["electrical", "breaker", "circuit", "safety", "power", "diy"],
    thumbnailUrl: "https://img.youtube.com/vi/v8Fqh7dJz6w/maxresdefault.jpg",
    duration: 245,
    likesCount: 45678,
    commentsEnabled: true,
    authorId: "youtube_creator3",
    authorName: "Everyday Home Repairs",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(2),
    isYouTube: true,
    youtubeId: "v8Fqh7dJz6w",
  },
  {
    id: "yt4",
    title: "How to Replace a Shower Head",
    description: "Easy DIY guide to replacing your old shower head with a new one. No plumber needed! Upgrade your bathroom in just 5 minutes.",
    category: "bathroom",
    tags: ["shower", "bathroom", "replace", "diy", "plumbing", "upgrade"],
    thumbnailUrl: "https://img.youtube.com/vi/ZL1n8kpI_hI/maxresdefault.jpg",
    duration: 320,
    likesCount: 32100,
    commentsEnabled: true,
    authorId: "youtube_creator4",
    authorName: "This Old House",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(3),
    isYouTube: true,
    youtubeId: "ZL1n8kpI_hI",
  },
  {
    id: "yt5",
    title: "How to Patch a Hole in Drywall",
    description: "Learn the professional way to repair small to medium holes in drywall. Perfect finish every time with these simple techniques.",
    category: "tools",
    tags: ["drywall", "wall", "repair", "patch", "diy", "home improvement"],
    thumbnailUrl: "https://img.youtube.com/vi/oCM8zCBZhb8/maxresdefault.jpg",
    duration: 540,
    likesCount: 89234,
    commentsEnabled: true,
    authorId: "youtube_creator5",
    authorName: "Vancouver Carpenter",
    isLiked: false,
    isSaved: false,
    createdAt: getDate(4),
    isYouTube: true,
    youtubeId: "oCM8zCBZhb8",
  },
];

export const getVideosByCategory = (category: string): Video[] => {
  if (category === "all") return sampleVideos;
  return sampleVideos.filter((v) => v.category === category);
};

export const getVideosByTag = (tag: string): Video[] => {
  const lowerTag = tag.toLowerCase();
  return sampleVideos.filter((v) =>
    v.tags.some((t) => t.toLowerCase().includes(lowerTag))
  );
};

export const searchVideos = (query: string, category?: string): Video[] => {
  const lowerQuery = query.toLowerCase();
  return sampleVideos.filter((v) => {
    const matchesQuery =
      v.title.toLowerCase().includes(lowerQuery) ||
      (v.description && v.description.toLowerCase().includes(lowerQuery)) ||
      v.tags.some((t) => t.toLowerCase().includes(lowerQuery));
    const matchesCategory = !category || category === "all" || v.category === category;
    return matchesQuery && matchesCategory;
  });
};

export const getCreatorVideos = (authorId: string): Video[] => {
  return sampleVideos.filter((v) => v.authorId === authorId);
};
