import { Video } from "./storage";

export const sampleVideos: Video[] = [
  {
    id: "sample1",
    uri: "",
    thumbnailUri: "",
    title: "Fix a Leaking Faucet in 45 Seconds",
    description: "Quick fix for a dripping kitchen or bathroom faucet. No plumber needed!",
    category: "plumbing",
    tags: ["faucet", "leak", "DIY", "plumbing"],
    authorId: "demo1",
    authorName: "FixItPro",
    duration: 45,
    likes: 234,
    commentsEnabled: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "sample2",
    uri: "",
    thumbnailUri: "",
    title: "Replace a Light Switch Safely",
    description: "Step-by-step guide to replacing a broken light switch.",
    category: "tools",
    tags: ["electrical", "switch", "DIY", "safety"],
    authorId: "demo2",
    authorName: "ElectricEase",
    duration: 58,
    likes: 189,
    commentsEnabled: true,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "sample3",
    uri: "",
    thumbnailUri: "",
    title: "Unclog a Drain Without Chemicals",
    description: "Natural method to clear a slow drain using household items.",
    category: "bathroom",
    tags: ["drain", "clog", "natural", "bathroom"],
    authorId: "demo1",
    authorName: "FixItPro",
    duration: 52,
    likes: 312,
    commentsEnabled: true,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: "sample4",
    uri: "",
    thumbnailUri: "",
    title: "Fix a Squeaky Door Hinge",
    description: "Stop that annoying squeak in seconds with this simple trick.",
    category: "tools",
    tags: ["door", "squeak", "hinge", "quick fix"],
    authorId: "demo3",
    authorName: "HomeHelper",
    duration: 28,
    likes: 456,
    commentsEnabled: true,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: "sample5",
    uri: "",
    thumbnailUri: "",
    title: "Change Your Car Oil Filter",
    description: "DIY oil filter replacement for most vehicle models.",
    category: "car",
    tags: ["car", "oil", "maintenance", "filter"],
    authorId: "demo4",
    authorName: "AutoFixer",
    duration: 60,
    likes: 278,
    commentsEnabled: true,
    createdAt: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: "sample6",
    uri: "",
    thumbnailUri: "",
    title: "Fix a Running Toilet",
    description: "Stop water waste with this quick toilet repair.",
    category: "plumbing",
    tags: ["toilet", "water", "fix", "bathroom"],
    authorId: "demo1",
    authorName: "FixItPro",
    duration: 55,
    likes: 198,
    commentsEnabled: true,
    createdAt: new Date(Date.now() - 518400000).toISOString(),
  },
  {
    id: "sample7",
    uri: "",
    thumbnailUri: "",
    title: "Clean Your Washing Machine",
    description: "Remove odors and buildup from your washer naturally.",
    category: "laundry",
    tags: ["washing machine", "clean", "maintenance", "laundry"],
    authorId: "demo5",
    authorName: "CleanQueen",
    duration: 48,
    likes: 567,
    commentsEnabled: true,
    createdAt: new Date(Date.now() - 604800000).toISOString(),
  },
  {
    id: "sample8",
    uri: "",
    thumbnailUri: "",
    title: "Sharpen Kitchen Knives at Home",
    description: "Keep your knives razor sharp with proper technique.",
    category: "kitchen",
    tags: ["knife", "sharpen", "kitchen", "tools"],
    authorId: "demo6",
    authorName: "ChefTools",
    duration: 42,
    likes: 345,
    commentsEnabled: true,
    createdAt: new Date(Date.now() - 691200000).toISOString(),
  },
  {
    id: "sample9",
    uri: "",
    thumbnailUri: "",
    title: "Reset Your Phone Battery Health",
    description: "Calibrate your phone battery for better performance.",
    category: "electronics",
    tags: ["phone", "battery", "electronics", "mobile"],
    authorId: "demo7",
    authorName: "TechTips",
    duration: 38,
    likes: 423,
    commentsEnabled: true,
    createdAt: new Date(Date.now() - 777600000).toISOString(),
  },
  {
    id: "sample10",
    uri: "",
    thumbnailUri: "",
    title: "Remove Grass Stains Easily",
    description: "Get rid of stubborn grass stains from clothes.",
    category: "cleaning",
    tags: ["stains", "laundry", "cleaning", "clothes"],
    authorId: "demo5",
    authorName: "CleanQueen",
    duration: 35,
    likes: 289,
    commentsEnabled: true,
    createdAt: new Date(Date.now() - 864000000).toISOString(),
  },
  {
    id: "sample11",
    uri: "",
    thumbnailUri: "",
    title: "Fix a Flat Tire in 5 Minutes",
    description: "Emergency roadside tire change when you're stranded.",
    category: "emergency",
    tags: ["tire", "car", "emergency", "roadside"],
    authorId: "demo4",
    authorName: "AutoFixer",
    duration: 58,
    likes: 892,
    commentsEnabled: true,
    createdAt: new Date(Date.now() - 950400000).toISOString(),
  },
  {
    id: "sample12",
    uri: "",
    thumbnailUri: "",
    title: "Stop a Water Leak Fast",
    description: "Quick emergency fix to stop water damage before the plumber arrives.",
    category: "emergency",
    tags: ["water", "leak", "emergency", "quick fix"],
    authorId: "demo1",
    authorName: "FixItPro",
    duration: 32,
    likes: 756,
    commentsEnabled: true,
    createdAt: new Date(Date.now() - 1036800000).toISOString(),
  },
];
